const RACE_HORSES_COUNT = 20;
const RACE_HORSES_PER_ROUND = 10;
const RACE_ROUNDS_COUNT = 6;
const RACE_ROUNDS_DISTANCES = [1200, 1400, 1600, 1800, 2000, 2200];
const RACE_ROUNDS_BREAK_INTERVAL = 2000;

export {
  RACE_HORSES_COUNT,
  RACE_HORSES_PER_ROUND,
  RACE_ROUNDS_COUNT,
  RACE_ROUNDS_DISTANCES,
  RACE_ROUNDS_BREAK_INTERVAL,
};
